M48
; DRILL file {KiCad (6.0.5)} date Thu Aug 18 11:16:57 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-18T11:16:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0374
%
G90
G05
T1
X5.7Y-3.4925
X5.7Y-3.5925
X5.7Y-3.7
X5.7Y-3.8
T2
X5.1Y-3.5
X5.1Y-3.5984
X5.1Y-3.6969
X5.1Y-3.7953
T0
M30
